import { computed, ref } from 'vue'

const locale = ref(localStorage.getItem('locale') || 'uz')

export const localeOptions = [
  { label: 'UZ', value: 'uz' },
  { label: 'RU', value: 'ru' },
  { label: 'EN', value: 'en' },
]

const messages = {
  uz: {
    nav: { info: "Ma'lumotlarim", infoCaption: "Shaxsiy ma'lumotlar", tasks: 'Vazifalarim', tasksCaption: 'Vazifalar boshqaruvi', inventory: 'Ombor va savdo', inventoryCaption: 'Kirim-chiqim boshqaruvi', discord: 'Discord chat', discordCaption: 'Chat kanali' },
    auth: { username: 'Foydalanuvchi nomi', password: 'Parol', submit: 'Kirish', loginSuccess: 'Tizimga muvaffaqiyatli kirildi' },
    profile: { username: 'Foydalanuvchi nomi', age: 'Yosh', region: 'Hudud', profession: 'Kasb', edit: 'Tahrirlash', save: 'Saqlash', changed: "Ma'lumotlar o'zgartirildi" },
    tasks: { selectType: 'Turni tanlang', dateFilter: 'Sana filtri', ok: 'OK', all: 'Barcha vazifalar', clear: 'Filtrni tozalash', add: 'Vazifa qo\'shish', updated: 'Vazifa yangilandi', updateError: 'Vazifani yangilab bo\'lmadi', added: 'Vazifa qo\'shildi', addError: 'Vazifani qo\'shib bo\'lmadi', deleted: 'Vazifa o\'chirildi', deleteError: 'Vazifani o\'chirib bo\'lmadi' },
    status: { registered: "Ro'yxatdan o'tgan", process: 'Jarayonda', completed: 'Tugallangan', testing: 'Test qilinmoqda', verified: 'Tasdiqlangan' },
    type: { high: 'Yuqori', normal: 'Oddiy', low: 'Past' },
    dialog: { edit: 'Tahrirlash', create: 'Yaratish', user: 'Foydalanuvchi', taskTitle: 'Vazifa nomi', description: 'Tavsif', deadline: 'Muddat', save: 'Saqlash' },
    validation: { required: 'Maydonni to\'ldiring' },
    error: { title: 'Bu yerda hech narsa yo\'q...', home: 'Bosh sahifa' },
    inventory: { eyebrow: 'SUPERMARKET CONTROL', title: 'Ombor va savdo markazi', subtitle: "Mahsulotlar, kirim-chiqim va moliyaviy ko'rsatkichlar bir joyda.", download: 'Hisobotni yuklash', addOperation: "Operatsiya qo'shish", todaySales: 'Bugungi savdo', todayPurchase: 'Bugungi kirim', stockValue: 'Ombor qiymati', lowStock: 'Kam qolganlar', salesOperations: 'ta sotuv operatsiyasi', purchaseOperations: 'ta qabul operatsiyasi', productTypes: 'ta mahsulot turi', needsAttention: 'Nazorat talab qiladi', overview: "Umumiy ko'rinish", products: 'Mahsulotlar', operations: 'Kirim-chiqim', reports: 'Hisobotlar', salesDynamics: 'Savdo dinamikasi', lastSevenDays: 'Oxirgi 7 kunlik tushum', warehouseDistribution: 'Ombor taqsimoti', categories: 'Kategoriyalar', latestOperations: "So'nggi operatsiyalar", latestActions: 'Eng yangi harakatlar', all: 'Barchasi', lowStockProducts: 'Kam qolgan mahsulotlar', belowMinimum: 'Minimal qoldiqdan past', allStockEnough: 'Barcha zaxiralar yetarli', noData: "Hozircha ma'lumot yo'q", noOperations: 'Operatsiyalar mavjud emas', catalog: 'Mahsulotlar katalogi', shownProducts: 'ta mahsulot ko\'rsatilmoqda', searchProduct: 'Mahsulot qidirish...', allCategories: 'Barcha kategoriyalar', addProduct: "Mahsulot qo'shish", category: 'Kategoriya', stock: 'Qoldiq', purchasePrice: 'Kirim narxi', salePrice: 'Sotuv narxi', edit: 'Tahrirlash', enterOutflow: 'Chiqim kiritish', journal: 'Kirim va chiqim jurnali', allMovements: 'Barcha ombor harakatlari', search: 'Qidirish...', type: 'Turi', product: 'Mahsulot', quantity: 'Miqdor', unitPrice: 'Birlik narxi', total: 'Jami', date: 'Sana', note: 'Izoh', incoming: 'Kirim', outgoing: 'Chiqim', monthlyReport: 'OYLIK HISOBOT', monthResults: 'natijalari', turnover: 'Sotuvlardan tushgan umumiy aylanma', estimatedProfit: 'Taxminiy foyda', soldProducts: 'Jami sotilgan mahsulot', dailyResults: 'Kunlik natijalar', currentMonth: "Joriy oy bo'yicha", newOperation: 'Yangi operatsiya', recordMovement: 'Ombor harakatini qayd eting', incomingShort: 'Kirim', outgoingSale: 'Chiqim / sotuv', selectProduct: 'Mahsulot *', save: 'Saqlash', cancel: 'Bekor qilish', newProduct: 'Yangi mahsulot', editProduct: 'Mahsulotni tahrirlash', catalogData: "Katalog ma'lumotlarini kiriting", productName: 'Mahsulot nomi *', sku: 'SKU / artikul *', unit: "O'lchov birligi", initialStock: "Boshlang'ich qoldiq", minimumStock: 'Minimal qoldiq', operationSaved: 'Operatsiya saqlandi', productUpdated: 'Mahsulot yangilandi', productAdded: "Mahsulot qo'shildi", outflowError: 'Chiqim miqdori qoldiqdan oshmasligi kerak', unknownProduct: "Noma'lum mahsulot", receivedProduct: 'Mahsulot qabul qilindi', saleOutflow: 'Sotuv chiqimi', dayUnit: 'dona', kgUnit: 'kg', literUnit: 'litr', boxUnit: 'quti', allDays: 'Jami' },
  },
  ru: {
    nav: { info: 'Мои данные', infoCaption: 'Личные данные', tasks: 'Мои задачи', tasksCaption: 'Управление задачами', inventory: 'Склад и продажи', inventoryCaption: 'Управление приходами и расходами', discord: 'Discord чат', discordCaption: 'Канал чата' },
    auth: { username: 'Имя пользователя', password: 'Пароль', submit: 'Войти', loginSuccess: 'Вход выполнен успешно' },
    profile: { username: 'Имя пользователя', age: 'Возраст', region: 'Регион', profession: 'Профессия', edit: 'Изменить', save: 'Сохранить', changed: 'Данные изменены' },
    tasks: { selectType: 'Выберите тип', dateFilter: 'Фильтр по дате', ok: 'ОК', all: 'Все задачи', clear: 'Очистить фильтр', add: 'Добавить задачу', updated: 'Задача обновлена', updateError: 'Не удалось обновить задачу', added: 'Задача добавлена', addError: 'Не удалось добавить задачу', deleted: 'Задача удалена', deleteError: 'Не удалось удалить задачу' },
    status: { registered: 'Зарегистрировано', process: 'В процессе', completed: 'Завершено', testing: 'Тестирование', verified: 'Проверено' },
    type: { high: 'Высокий', normal: 'Обычный', low: 'Низкий' },
    dialog: { edit: 'Изменить', create: 'Создать', user: 'Пользователь', taskTitle: 'Название задачи', description: 'Описание', deadline: 'Срок', save: 'Сохранить' },
    validation: { required: 'Заполните поле' },
    error: { title: 'Здесь ничего нет...', home: 'На главную' },
    inventory: { eyebrow: 'SUPERMARKET CONTROL', title: 'Склад и торговый центр', subtitle: 'Товары, приходы, расходы и финансовые показатели в одном месте.', download: 'Скачать отчет', addOperation: 'Добавить операцию', todaySales: 'Продажи сегодня', todayPurchase: 'Приход сегодня', stockValue: 'Стоимость склада', lowStock: 'Малый остаток', salesOperations: 'операций продаж', purchaseOperations: 'операций приема', productTypes: 'видов товаров', needsAttention: 'Требует внимания', overview: 'Обзор', products: 'Товары', operations: 'Приходы и расходы', reports: 'Отчеты', salesDynamics: 'Динамика продаж', lastSevenDays: 'Выручка за последние 7 дней', warehouseDistribution: 'Распределение склада', categories: 'Категории', latestOperations: 'Последние операции', latestActions: 'Новые движения', all: 'Все', lowStockProducts: 'Товары с малым остатком', belowMinimum: 'Ниже минимального остатка', allStockEnough: 'Все запасы достаточны', noData: 'Данных пока нет', noOperations: 'Операций нет', catalog: 'Каталог товаров', shownProducts: 'товаров показано', searchProduct: 'Поиск товара...', allCategories: 'Все категории', addProduct: 'Добавить товар', category: 'Категория', stock: 'Остаток', purchasePrice: 'Цена прихода', salePrice: 'Цена продажи', edit: 'Изменить', enterOutflow: 'Внести расход', journal: 'Журнал приходов и расходов', allMovements: 'Все движения склада', search: 'Поиск...', type: 'Тип', product: 'Товар', quantity: 'Количество', unitPrice: 'Цена за единицу', total: 'Итого', date: 'Дата', note: 'Примечание', incoming: 'Приход', outgoing: 'Расход', monthlyReport: 'ОТЧЕТ ЗА МЕСЯЦ', monthResults: 'результаты', turnover: 'Общий оборот продаж', estimatedProfit: 'Примерная прибыль', soldProducts: 'Всего продано товаров', dailyResults: 'Результаты по дням', currentMonth: 'За текущий месяц', newOperation: 'Новая операция', recordMovement: 'Запишите движение склада', incomingShort: 'Приход', outgoingSale: 'Расход / продажа', selectProduct: 'Товар *', save: 'Сохранить', cancel: 'Отмена', newProduct: 'Новый товар', editProduct: 'Изменить товар', catalogData: 'Введите данные каталога', productName: 'Название товара *', sku: 'SKU / артикул *', unit: 'Единица измерения', initialStock: 'Начальный остаток', minimumStock: 'Минимальный остаток', operationSaved: 'Операция сохранена', productUpdated: 'Товар обновлен', productAdded: 'Товар добавлен', outflowError: 'Количество расхода не может превышать остаток', unknownProduct: 'Неизвестный товар', receivedProduct: 'Товар принят', saleOutflow: 'Продажа', dayUnit: 'шт.', kgUnit: 'кг', literUnit: 'л', boxUnit: 'кор.', allDays: 'Всего' },
  },
  en: {
    nav: { info: 'My info', infoCaption: 'Personal information', tasks: 'My tasks', tasksCaption: 'Task management', inventory: 'Inventory & sales', inventoryCaption: 'Inflow and outflow management', discord: 'Discord chat', discordCaption: 'Chat channel' },
    auth: { username: 'Username', password: 'Password', submit: 'Submit', loginSuccess: 'Login successful' },
    profile: { username: 'Username', age: 'Age', region: 'Region', profession: 'Profession', edit: 'Edit', save: 'Save', changed: 'Information changed' },
    tasks: { selectType: 'Select type', dateFilter: 'Date filter', ok: 'OK', all: 'All tasks', clear: 'Clear filter', add: 'Add task', updated: 'Task updated', updateError: 'Task could not be updated', added: 'Task added', addError: 'Task could not be added', deleted: 'Task deleted', deleteError: 'Task could not be deleted' },
    status: { registered: 'Registered', process: 'In process', completed: 'Completed', testing: 'Testing', verified: 'Verified' },
    type: { high: 'High', normal: 'Normal', low: 'Low' },
    dialog: { edit: 'Edit', create: 'Create', user: 'User', taskTitle: 'Task title', description: 'Description', deadline: 'Deadline', save: 'Save' },
    validation: { required: 'Please type something' },
    error: { title: 'Oops. Nothing here...', home: 'Go Home' },
    inventory: { eyebrow: 'SUPERMARKET CONTROL', title: 'Warehouse and sales center', subtitle: 'Products, stock movements, and financial metrics in one place.', download: 'Download report', addOperation: 'Add operation', todaySales: 'Today\'s sales', todayPurchase: 'Today\'s purchases', stockValue: 'Inventory value', lowStock: 'Low stock', salesOperations: 'sales operations', purchaseOperations: 'receiving operations', productTypes: 'product types', needsAttention: 'Needs attention', overview: 'Overview', products: 'Products', operations: 'Inflow and outflow', reports: 'Reports', salesDynamics: 'Sales dynamics', lastSevenDays: 'Revenue for the last 7 days', warehouseDistribution: 'Inventory distribution', categories: 'Categories', latestOperations: 'Recent operations', latestActions: 'Latest movements', all: 'All', lowStockProducts: 'Low-stock products', belowMinimum: 'Below minimum stock', allStockEnough: 'All stock levels are sufficient', noData: 'No data yet', noOperations: 'No operations', catalog: 'Product catalog', shownProducts: 'products shown', searchProduct: 'Search products...', allCategories: 'All categories', addProduct: 'Add product', category: 'Category', stock: 'Stock', purchasePrice: 'Purchase price', salePrice: 'Sale price', edit: 'Edit', enterOutflow: 'Record outflow', journal: 'Inflow and outflow journal', allMovements: 'All inventory movements', search: 'Search...', type: 'Type', product: 'Product', quantity: 'Quantity', unitPrice: 'Unit price', total: 'Total', date: 'Date', note: 'Note', incoming: 'Inflow', outgoing: 'Outflow', monthlyReport: 'MONTHLY REPORT', monthResults: 'results', turnover: 'Total sales turnover', estimatedProfit: 'Estimated profit', soldProducts: 'Products sold', dailyResults: 'Daily results', currentMonth: 'For the current month', newOperation: 'New operation', recordMovement: 'Record inventory movement', incomingShort: 'Inflow', outgoingSale: 'Outflow / sale', selectProduct: 'Product *', save: 'Save', cancel: 'Cancel', newProduct: 'New product', editProduct: 'Edit product', catalogData: 'Enter catalog details', productName: 'Product name *', sku: 'SKU / item number *', unit: 'Unit', initialStock: 'Initial stock', minimumStock: 'Minimum stock', operationSaved: 'Operation saved', productUpdated: 'Product updated', productAdded: 'Product added', outflowError: 'Outflow quantity cannot exceed stock', unknownProduct: 'Unknown product', receivedProduct: 'Product received', saleOutflow: 'Sale outflow', dayUnit: 'pcs', kgUnit: 'kg', literUnit: 'l', boxUnit: 'box', allDays: 'Total' },
  },
}

export function useI18n() {
  const t = (key) => key.split('.').reduce((value, part) => value?.[part], messages[locale.value]) || key
  const setLocale = (value) => {
    if (!messages[value]) return
    locale.value = value
    localStorage.setItem('locale', value)
  }

  return { locale, localeOptions, t, setLocale, currentLocale: computed(() => locale.value) }
}
